---


- include_tasks: components/tlu_aida.yml
  when:
    eudaq_tlu_aida.build

- include_tasks: components/tlu_eudet.yml
  when:
    eudaq_tlu_eudet.build

- name: Component TLU
  set_fact:
    eudaq_cmake_options: "{{ eudaq_cmake_options|default() }} -DUSER_TLU_BUILD=ON  -DUSER_TLU_BUILD_AIDA={{ 'ON' if eudaq_tlu_aida.build else 'OFF'}} -DUSER_TLU_BUILD_EUDET={{ 'ON' if eudaq_tlu_eudet.build else 'OFF'}}"
  when:
    eudaq_tlu_aida.build or eudaq_tlu_eudet.build

- name: Component EUDET
  set_fact:
    eudaq_cmake_options: "{{ eudaq_cmake_options|default() }} -DUSER_EUDET_BUILD=ON"
  when:
    eudaq_build_eudet

- include_tasks: components/caribou.yml
  when:
    eudaq_build_caribou

- name: Component Caribou
  set_fact:
    eudaq_cmake_options: "{{ eudaq_cmake_options|default() }} -DUSER_CARIBOU_BUILD=ON"
  when:
    eudaq_build_caribou

- include_tasks: components/pistage.yml
  when:
    eudaq_build_pistage

- name: Component PIStage
  set_fact:
    eudaq_cmake_options: "{{ eudaq_cmake_options|default() }} -DUSER_PISTAGE_BUILD=ON"
  when:
    eudaq_build_pistage
