---
# tasks file for eudaq

- name: Make sure EUDAQ2 build dependencies are present
  apt:
    name: ['git', 'g++', 'cmake']

- name: Delete old build folder
  file:
    path: "{{ eudaq_build_folder }}"
    state: absent

- name: Clone EUDAQ2 repository
  git:
    repo: "{{ eudaq_repository }}"
    version: "{{ eudaq_branch }}"
    accept_hostkey: yes
    depth: 1
    force: yes
    dest: "{{ eudaq_build_folder }}"

- name: Create build folder
  file:
    path: "{{ eudaq_build_folder }}/build"
    state: directory

- include_tasks: components.yml

- name: Configure EUDAQ2 build
  shell: "{{ item }}"
  args:
    chdir: "{{ eudaq_build_folder }}/build"
  with_items:
    - cmake -DEUDAQ_INSTALL_PREFIX="{{ eudaq_install_folder }}" -DEUDAQ_BUILD_EXECUTABLE={{ 'ON' if eudaq_build_executables else 'OFF'}} -DEUDAQ_BUILD_GUI={{ 'ON' if eudaq_build_gui else 'OFF'}} -DEUDAQ_BUILD_STDEVENT_MONITOR={{ 'ON' if eudaq_build_stdevent_monitor else 'OFF'}} {{ eudaq_cmake_options }} ..

- name: Build EUDAQ2
  shell: "make -j{{ ansible_processor_vcpus|default(ansible_processor_count) }}"
  args:
    chdir: "{{ eudaq_build_folder }}/build"

- name: Install EUDAQ2
  make:
    chdir: "{{ eudaq_build_folder }}/build"
    target: install
    params:
      NUM_THREADS: "{{ ansible_processor_vcpus|default(ansible_processor_count) }}"
