---
# tasks file for eudaq

- name: Make sure EUDAQ2 build dependencies are present
  apt:
    name: ['git', 'g++', 'cmake']

- name: Clone EUDAQ2 repository
  git:
    repo: "{{ eudaq_repository }}"
    version: "{{ eudaq_branch }}"
    accept_hostkey: yes
    depth: 1
    force: yes
    dest: "{{ eudaq_build_folder }}"

- name: Configure EUDAQ2 build
  shell: "{{ item }}"
  args:
    chdir: "{{ eudaq_build_folder }}"
  with_items:
    - ./build.sh
    - ./configure


- name: Build and install EUDAQ2
  shell: "{{ item }}"
  args:
    chdir: "{{ eudaq_build_folder }}"
  with_items:
    - make -j{{ ansible_processor_vcpus|default(ansible_processor_count) }}
    - make install
